const $=id=>document.getElementById(id);const NS='http://www.w3.org/2000/svg';const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let state='home',floor=4,selected=null,hovered=null,view=0,mode='day',introTimer=null,cycleTimer=null,activeTab='render',project={units:[]};
const high=[
 {letter:'A',label:[555,635],points:[[153,444],[755,444],[755,839],[373,839],[373,754],[112,754],[120,528],[153,528]]},
 {letter:'B',label:[1110,635],points:[[914,444],[1515,444],[1515,528],[1554,528],[1562,754],[1290,754],[1290,839],[914,839]]},
 {letter:'C',label:[555,275],points:[[136,139],[382,139],[382,79],[755,79],[755,431],[153,431],[153,350],[132,350]]},
 {letter:'D',label:[1110,275],points:[[914,79],[1273,79],[1273,139],[1534,139],[1534,350],[1515,350],[1515,431],[914,431]]}
];
const ground=[
 {letter:'L1',label:[525,510],points:[[258,185],[509,185],[509,124],[781,124],[781,782],[503,782],[503,719],[268,719],[268,558],[309,558],[309,380],[258,380]]},
 {letter:'L2',label:[1305,510],points:[[1028,126],[1402,126],[1402,182],[1662,182],[1662,544],[1680,544],[1680,720],[1402,720],[1402,785],[1028,785]]}
];
const units=()=>floor===0?ground:high;const unitId=i=>floor===0?`PB-${i+1}`:`${floor}${high[i].letter}`;const unitTitle=i=>floor===0?`Local ${i+1}`:`Unidad ${unitId(i)}`;
function data(i){return project.units.find(u=>u.id===unitId(i))||{status:'available',rooms:floor===0?null:2,bedrooms:floor===0?0:1,bathrooms:1,balcony:floor===0?false:true,kitchen:floor===0?'Office':'Sí'};}
function status(i){const u=data(i);return {label:({available:'Disponible',sold:'Vendida',reserved:'Reservada'})[u.status]||'Disponibilidad a confirmar',color:({available:'#1dac70',sold:'#e92236',reserved:'#c18d38'})[u.status]||'#ba913e'};}
const show=(id,on)=>$(id).hidden=!on;function context(){return floor===0?'Planta baja · Locales comerciales':`Piso ${floor} · 4 departamentos`;}
fetch('./project.json').then(r=>r.json()).then(async d=>{project=d;if(d.availabilityEndpoint){try{const r=await fetch(d.availabilityEndpoint);if(!r.ok)throw Error(r.status);const rows=await r.json();if(Array.isArray(rows))project.units=project.units.map(u=>({...u,...rows.find(v=>v.id===u.id)}));}catch(e){console.warn('Disponibilidad pendiente',e);}}applyMedia();if(state==='floors')renderPlan();else if(state==='detail')openDetails();}).catch(console.error);
for(const m of ['day','night'])for(let i=0;i<6;i++){const image=new Image();image.src=`assets/site-exterior-${m}-${i}.webp`;}
function setMode(value){mode=value;$('nightImage').style.opacity=value==='night'?'1':'0';$('day').setAttribute('aria-pressed',value==='day');$('night').setAttribute('aria-pressed',value==='night');}
function setView(value){view=(value+6)%6;const front=state==='home',media=project.media||{},images=front?media.cover:media.exterior?.[view];$('dayImage').src=images?.day||(front?'assets/site-front-day.webp':`assets/site-exterior-day-${view}.webp`);$('nightImage').src=images?.night||(front?'assets/site-front-night.webp':`assets/site-exterior-night-${view}.webp`);$('dayImage').alt=`Vista exterior ${view+1} del edificio, de día`;$('nightImage').alt=`Vista exterior ${view+1} del edificio, de noche`;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.view===view));}
for(let i=0;i<6;i++){const b=document.createElement('button');b.dataset.view=i;b.textContent=i+1;b.setAttribute('aria-label',`Vista ${i+1} del edificio`);b.onclick=()=>setView(i);$('viewDots').appendChild(b);}
function stopIntro(){clearTimeout(introTimer);$('arrivalVideo').pause();$('app').classList.remove('entering','intro-fallback');show('intro',false);if(state==='exterior'){show('exteriorControls',true);show('dayControls',true);show('floorsBtn',true);show('hint',true);}}
function route(next,keepBuildingTransition=false){if(!keepBuildingTransition)cancelBuildingEntry();stopIntro();clearInterval(cycleTimer);state=next;selected=null;hovered=null;$('app').dataset.screen=next;show('exteriorStage',next==='home'||next==='exterior');show('welcome',next==='home');show('back',next!=='home');show('context',next!=='home');show('floorsBtn',next==='exterior');show('dayControls',next==='exterior');show('exteriorControls',next==='exterior');show('floorStage',next==='floors');show('floorRail',next==='floors');show('floorCadBtn',next==='floors');show('details',false);show('unitPreview',false);show('hint',next!=='home');$('hint').textContent=next==='floors'?'Pasá el cursor o tocá una unidad':'Elegí un ángulo para recorrer el exterior';$('context').textContent=next==='floors'?context():'Proyecto Inmobiliario';if(next==='home'){setView(0);setMode('day');cycleTimer=setInterval(()=>setMode(mode==='day'?'night':'day'),7500);}else if(next==='exterior'){setView(view);}else if(next==='floors'){floor=4;renderPlan();}history.replaceState(null,'','#'+next);}
function useIntroFallback(){if(!$('app').classList.contains('entering'))return;$('app').classList.add('intro-fallback');clearTimeout(introTimer);introTimer=setTimeout(stopIntro,6800);}
function enter(){route('exterior');setView(0);setMode('day');show('exteriorControls',false);show('dayControls',false);show('floorsBtn',false);show('hint',false);show('intro',true);void $('app').offsetWidth;$('app').classList.add('entering');const video=$('arrivalVideo');video.currentTime=0;video.play().catch(useIntroFallback);introTimer=setTimeout(stopIntro,10000);}
$('arrivalVideo').onended=stopIntro;$('arrivalVideo').onerror=useIntroFallback;
function renderPlan(){updateFloorBackground();const isGround=floor===0;$('floorOutline').setAttribute('points',isGround?floorOutlines.ground:floorOutlines.high);$('plan').setAttribute('viewBox',isGround?'0 0 1730 909':'0 0 1672 941');$('planImage').setAttribute('href',isGround?'assets/floor-ground.png':'assets/floor-high.png');$('planImage').setAttribute('width',isGround?1730:1672);$('planImage').setAttribute('height',isGround?909:941);$('hotspots').replaceChildren();$('planLabels').replaceChildren();units().forEach((u,i)=>{const polygon=document.createElementNS(NS,'polygon');polygon.setAttribute('points',u.points.map(p=>p.join(',')).join(' '));polygon.dataset.unit=i;polygon.setAttribute('tabindex','0');polygon.setAttribute('role','button');polygon.setAttribute('aria-label',`Ver ${unitTitle(i)}`);polygon.style.setProperty('--status-color',status(i).color);polygon.style.setProperty('--status-fill',status(i).color+'33');polygon.addEventListener('pointerenter',()=>previewUnit(i,false));polygon.addEventListener('focus',()=>previewUnit(i,false));polygon.addEventListener('click',()=>previewUnit(i,true));polygon.addEventListener('dblclick',()=>{previewUnit(i,true);openDetails();});polygon.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();previewUnit(i,true);}});$('hotspots').appendChild(polygon);const b=document.createElement('button');b.className='unit-label';b.dataset.unit=i;b.setAttribute('aria-label',`Ver ${unitTitle(i)}`);b.innerHTML=`<i style="background:${status(i).color}"></i><span>${floor===0?'Local '+(i+1):unitId(i)}</span>`;b.style.setProperty('--status-color',status(i).color);b.onclick=()=>previewUnit(i,true);b.ondblclick=()=>{previewUnit(i,true);openDetails();};b.onmouseenter=()=>previewUnit(i,false);$('planLabels').appendChild(b);});$('context').textContent=context();document.querySelectorAll('[data-floor]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.floor===floor));requestAnimationFrame(positionLabels);}
function positionLabels(){if(state!=='floors')return;const matrix=$('plan').getScreenCTM();if(!matrix)return;units().forEach((u,i)=>{const p=$('plan').createSVGPoint();[p.x,p.y]=u.label;const out=p.matrixTransform(matrix),b=$('planLabels').children[i];if(b){b.style.left=out.x+'px';b.style.top=out.y+'px';}});}
function highlight(i){document.querySelectorAll('[data-unit]').forEach(el=>el.classList.toggle('active',+el.dataset.unit===i));}
function previewUnit(i,lock){hovered=i;if(lock)selected=i;highlight(i);$('previewFloor').textContent=floor===0?'PLANTA BAJA':`PISO ${floor}`;$('previewName').textContent=unitTitle(i);$('previewRooms').textContent=floor===0?'Local comercial · Office · Baño':'2 ambientes · 1 dormitorio · Balcón';$('previewStatus').textContent=status(i).label;$('previewStatus').style.color=status(i).color;$('previewStatus').style.backgroundColor=status(i).color+'18';show('unitPreview',true);}
function setFloor(value){floor=value;selected=null;hovered=null;show('unitPreview',false);renderPlan();}
function closePreview(){selected=null;hovered=null;highlight(-1);show('unitPreview',false);}
const confirmed=v=>v===null||v===undefined?'A confirmar':typeof v==='boolean'?(v?'Sí':'No'):v;
function openDetails(){const i=hovered??selected;if(i===null)return;selected=i;state='detail';$('app').dataset.screen='detail';show('floorStage',false);show('floorRail',false);show('floorCadBtn',false);show('unitPreview',false);show('hint',false);show('details',true);$('context').textContent=`${floor===0?'Planta baja':'Piso '+floor} / ${unitTitle(i)}`;$('detailName').textContent=unitTitle(i);$('detailStatus').textContent=status(i).label;$('detailStatus').style.color=status(i).color;$('detailStatus').style.backgroundColor=status(i).color+'18';const d=data(i),area=v=>typeof v==='number'?v.toLocaleString('es-AR')+' m²':'A confirmar';const commercial=floor===0||d.type==='commercial';const fields=[['Superficie total',area(d.totalArea)],['Piso',floor===0?'Planta baja':floor],...(!commercial?[['Ambientes',confirmed(d.rooms)],['Dormitorios',confirmed(d.bedrooms)]]:[]),['Baños',confirmed(d.bathrooms)],...(!commercial?[['Balcón',confirmed(d.balcony)],['Cocina',confirmed(d.kitchen)]]:[]),['Cochera',d.parking!=null?confirmed(d.parking):project.buildingParking?'Sí':'A confirmar']];$('detailFields').replaceChildren();fields.forEach(([key,value])=>{const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;div.append(dt,dd);$('detailFields').appendChild(div);});selectTab('render');history.replaceState(null,'',`#unidad-${unitId(i)}`);}
function selectTab(tab){activeTab=tab;const balcony=tab==='views'&&floor>0?project.media?.balconyViews?.[unitId(selected)]:null;show('balconyPanel',!!balcony);document.querySelectorAll('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',b.dataset.tab===tab);b.setAttribute('tabindex',b.dataset.tab===tab?'0':'-1');b.setAttribute('aria-controls',b.dataset.tab==='render'?'renderPanel':b.dataset.tab==='cad'?'pdfPanel':b.dataset.tab==='views'&&balcony?'balconyPanel':'emptyPanel');});show('renderPanel',tab==='render');show('emptyPanel',tab==='gallery'||(tab==='views'&&!balcony));show('pdfPanel',tab==='cad');if(balcony){$('balconyImage').src=balcony.src;$('balconyImage').alt='Simulación de la vista desde el balcón de '+unitTitle(selected);$('balconyTitle').textContent='Balcón · '+unitTitle(selected)+' · Piso '+floor;$('balconyOrientation').textContent=balcony.orientation;}else if(tab==='render'){renderUnitPlan();}else if(tab==='cad'){const base=floor===0?'local-'+(selected+1):'unit-'+high[selected].letter.toLowerCase();$('pdfTitle').textContent='Plano CAD · '+unitTitle(selected);$('pdfOpen').href=`assets/${base}.pdf`;$('pdfDownload').href=`assets/${base}.pdf`;$('pdfPreview').src=`assets/cad-${base}.png`;$('pdfPreview').alt='Plano CAD individual · '+unitTitle(selected);$('pdfPreview').parentElement.classList.remove('zoomed');}else{$('emptyIcon').textContent=tab==='gallery'?'▧':'◫';$('emptyTitle').textContent=tab==='gallery'?'Galería de la unidad':floor===0?'Vistas del local':'Vistas desde el balcón';$('emptyDescription').textContent=tab==='gallery'?'Las fotografías y renders se incorporarán próximamente.':'Las imágenes de las vistas se incorporarán próximamente.';}}
let buildingTimer=null;
function cancelBuildingEntry(){clearTimeout(buildingTimer);$('buildingVideo').pause();show('buildingTransition',false);$('buildingTransition').classList.remove('reveal-floor','building-fallback');$('app').classList.remove('ascending');}
function finishBuildingEntry(){if(!$('app').classList.contains('ascending'))return;clearTimeout(buildingTimer);$('buildingVideo').pause();route('floors',true);$('app').classList.remove('ascending');$('buildingTransition').classList.add('reveal-floor');buildingTimer=setTimeout(cancelBuildingEntry,1150);}
function buildingFallback(){if(!$('app').classList.contains('ascending'))return;$('buildingTransition').classList.add('building-fallback');clearTimeout(buildingTimer);buildingTimer=setTimeout(finishBuildingEntry,1800);}
function enterBuilding(){if(state!=='exterior'||$('app').classList.contains('ascending'))return;stopIntro();const video=$('buildingVideo'),poster=`assets/site-exterior-${mode}-${view}.webp`;video.poster=poster;$('buildingFallback').src=poster;video.src=`assets/site-building-entry-${mode}-${view}.webm`;$('app').classList.add('ascending');show('buildingTransition',true);buildingTimer=setTimeout(finishBuildingEntry,9000);video.play().catch(buildingFallback);}
function openFloorCad(){const groundFloor=floor===0,base=groundFloor?'floor-ground':'floor-high';$('floorCadTitle').textContent=(groundFloor?'Planta baja':'Piso '+floor)+' · Plano CAD';$('floorCadOpen').href=`assets/${base}.pdf`;$('floorCadDownload').href=`assets/${base}.pdf`;$('floorCadPreview').src=`assets/cad-${groundFloor?'ground':'high'}.png`;$('floorCadPreview').alt='Plano CAD de la planta completa';$('floorCadPreview').parentElement.classList.remove('zoomed');$('floorCad').showModal();}
$('floorCadBtn').onclick=openFloorCad;$('floorCadPreview').onclick=()=>$('floorCadPreview').parentElement.classList.toggle('zoomed');$('buildingVideo').onended=finishBuildingEntry;$('buildingVideo').onerror=buildingFallback;$('skipBuilding').onclick=finishBuildingEntry;
$('enter').onclick=enter;$('skipIntro').onclick=stopIntro;$('floorsBtn').onclick=$('buildingEntry').onclick=enterBuilding;$('back').onclick=()=>{if(state==='detail'){const f=floor;route('floors');setFloor(f);}else route(state==='floors'?'exterior':'home');};$('day').onclick=()=>setMode('day');$('night').onclick=()=>setMode('night');$('previous').onclick=()=>setView(view-1);$('next').onclick=()=>setView(view+1);$('exteriorStage').onclick=()=>{if(state==='exterior'&&!$('app').classList.contains('entering')&&!$('app').classList.contains('ascending'))setView(view+1);};$('closePreview').onclick=closePreview;$('moreDetails').onclick=openDetails;$('contactBtn').onclick=()=>{const email=project.contactEmail;if(typeof email==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){location.href='mailto:'+encodeURIComponent(email)+'?subject='+encodeURIComponent('Consulta por '+unitTitle(selected)+' · Proyecto Inmobiliario');return;}$('notice').textContent='El medio de contacto se incorporará próximamente.';show('notice',true);setTimeout(()=>show('notice',false),3500);};document.querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>setFloor(+b.dataset.floor));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>selectTab(b.dataset.tab));$('mediaTabs').onkeydown=e=>{const tabs=[...document.querySelectorAll('[data-tab]')],i=tabs.findIndex(b=>b.dataset.tab===activeTab);let n;if(['ArrowDown','ArrowRight'].includes(e.key))n=(i+1)%4;if(['ArrowUp','ArrowLeft'].includes(e.key))n=(i+3)%4;if(e.key==='Home')n=0;if(e.key==='End')n=3;if(n!==undefined){e.preventDefault();selectTab(tabs[n].dataset.tab);tabs[n].focus();}};$('pdfPreview').onclick=()=>{$('pdfPreview').parentElement.classList.toggle('zoomed');};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('notice').textContent='Usá la opción de pantalla completa de tu navegador.';show('notice',true);setTimeout(()=>show('notice',false),3500);}};
$('menuBtn').onclick=()=>{$('menu').showModal();$('menuBtn').setAttribute('aria-expanded','true');};$('menu').onclose=()=>$('menuBtn').setAttribute('aria-expanded','false');document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{$('menu').close();const dest=b.dataset.nav;if(['home','exterior','floors'].includes(dest))route(dest);else{if(dest==='location')$('infoContent').innerHTML='<p class="eyebrow">TIERRA DEL FUEGO · ARGENTINA</p><h2>Río Grande</h2><p>Presidente Bernardino Rivadavia 417</p><iframe title="Ubicación del proyecto" loading="lazy" src="https://maps.google.com/maps?q=Presidente%20Bernardino%20Rivadavia%20417%2C%20Rio%20Grande%2C%20Tierra%20del%20Fuego%2C%20Argentina&output=embed"></iframe><p><a href="https://www.google.com/maps/search/?api=1&query=Presidente+Bernardino+Rivadavia+417+Rio+Grande+Tierra+del+Fuego" target="_blank" rel="noopener">Abrir en Google Maps ↗</a></p>';else $('infoContent').innerHTML='<p class="eyebrow">SOBRE ESTA VERSIÓN</p><h2>Proyecto Inmobiliario</h2><p>Las plantas utilizan las imágenes y los PDF del material comercial del proyecto. El exterior presenta seis vistas fijas del modelo original, de día y de noche.</p><p>La galería está preparada para incorporar las imágenes definitivas. Las vistas de los balcones son simulaciones por unidad y piso a partir del modelo, con entorno aproximado. La disponibilidad es de muestra: una unidad vendida por piso y un local vendido en planta baja. Los departamentos y locales cuentan con cochera. Cada departamento tiene 57,67 m²; el Local 1, 93,45 m²; y el Local 2, 113,35 m².</p><p>La entrada desciende desde una vista aérea del modelo, atraviesa nubes y llega al edificio. Las vistas y animaciones incorporan el terreno, las calles y los volúmenes vecinos preparados en SketchUp. El entorno es una representación simplificada con alturas aproximadas; los renders fotorealistas se incorporarán con las imágenes definitivas. La iluminación de las vistas exteriores es de presentación.</p>';$('info').showModal();}});
window.addEventListener('resize',positionLabels);new ResizeObserver(positionLabels).observe($('floorStage'));window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(state==='exterior'&&!$('app').classList.contains('entering')&&!$('app').classList.contains('ascending')){if(e.key==='ArrowLeft')setView(view-1);if(e.key==='ArrowRight')setView(view+1);}});

const floorOutlines={
 high:'756,17 914,17 914,77 1274,77 1274,137 1537,137 1542,356 1524,356 1524,526 1555,526 1562,769 1300,769 1300,850 912,850 912,788 754,788 754,850 370,850 370,769 106,769 117,525 145,525 145,356 128,356 136,136 380,136 380,77 756,77',
 ground:'878,17 1038,17 1038,122 1402,122 1402,179 1662,179 1662,403 1633,403 1633,537 1663,537 1663,748 1403,748 1403,804 1027,804 1027,738 897,738 897,804 500,804 500,748 258,748 258,571 24,571 24,368 255,368 255,179 509,179 509,123 878,123'
};
for(const src of ['assets/floor-high.png','assets/floor-ground.png']){const img=new Image();img.src=src;img.decode().catch(()=>{});}
setView(0);const hash=location.hash.slice(1);if(hash.startsWith('unidad-')){const id=hash.slice(7);floor=id.startsWith('PB-')?0:parseInt(id);floor=Number.isFinite(floor)&&floor>=0&&floor<=4?floor:4;hovered=id.startsWith('PB-')?Math.max(0,Math.min(1,parseInt(id.at(-1))-1)):Math.max(0,high.findIndex(u=>u.letter===id.at(-1)));show('exteriorStage',false);show('welcome',false);show('back',true);show('context',true);openDetails();}else route(['floors','exterior'].includes(hash)?hash:'home');

function renderUnitPlan(){
 const u=units()[selected],xs=u.points.map(p=>p[0]),ys=u.points.map(p=>p[1]),pad=30;
 const x=Math.min(...xs)-pad,y=Math.min(...ys)-pad,w=Math.max(...xs)-x+pad,h=Math.max(...ys)-y+pad,groundFloor=floor===0;
 $('renderPanel').innerHTML=`<svg xmlns="${NS}" role="img" aria-label="Plano 3D de ${unitTitle(selected)}" viewBox="${x} ${y} ${w} ${h}"><defs><mask id="unitRenderMask" maskUnits="userSpaceOnUse" x="${x}" y="${y}" width="${w}" height="${h}"><polygon points="${u.points.map(p=>p.join(',')).join(' ')}" fill="white" stroke="white" stroke-width="24" stroke-linejoin="round"/></mask></defs><image mask="url(#unitRenderMask)" href="assets/${groundFloor?'floor-ground':'floor-high'}.png" width="${groundFloor?1730:1672}" height="${groundFloor?909:941}"/></svg>`;
}
function applyMedia(){if(project.media?.arrivalVideo)$('arrivalVideo').src=project.media.arrivalVideo;setView(view);}
function updateFloorBackground(){
 const source=project.media?.floorBackgrounds?.[floor];
 const backdrop=$('floorBackdrop'),previous=backdrop.style.backgroundImage,next=source?`url(${JSON.stringify(source)})`:'none';backdrop.replaceChildren();backdrop.style.backgroundImage=next;if(previous&&previous!=='none'&&previous!==next){const fade=document.createElement('div');Object.assign(fade.style,{position:'absolute',inset:'0',backgroundImage:previous,backgroundSize:'cover',backgroundPosition:'center'});backdrop.appendChild(fade);fade.animate([{opacity:1},{opacity:0}],{duration:650,fill:'forwards'}).onfinish=()=>fade.remove();}
 // Per-floor images must be aligned to the same plan camera before publication.
 $('floorBackdrop').dataset.hasImage=Boolean(source);
}
